### ISSUE TITLE
[Fabric] Can't start BMC server when PC language is set to certain languages

### ISSUE THREAD

**Issue by jmadarg** [AkashiiKun/MoreAxolotlVariantsMod-Common#18]
When the PC language is set to Turkish and you try to run a BetterMC the server, it is not able to start because of mavm, specifically with this error:

![image](https://user-images.githubusercontent.com/62086445/215870748-f844f198-f17f-47cd-ae8e-62d05564a0c5.png)

Seems to have problems with the name `lucıa` 
![image](https://user-images.githubusercontent.com/62086445/215872837-b17b3213-5412-4f61-8702-9134f547128a.png)

Its the second time I've seen this reported on the Luna Pixel Studios' discord, the first time was also with Turkish and this was their log: https://mclo.gs/acYy5kG

Minecraft version: 1.19.2

**Comment by AkashiiKun** [comment]
Could you tell me if the test jar file inside this zip fixes the crash? Hope it works. Please tell me so i can release the fix.
[More Axolotl Variants Mod Locale Fix.zip](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10556553/More.Axolotl.Variants.Mod.Locale.Fix.zip)

**Comment by jmadarg** [comment]
Thanks for the quick fix! The person having the issue is gonna test it later because they are at work rn

**Comment by AkashiiKun** [comment]
Alright.

**Comment by jmadarg** [comment]
The person who had the issue hasn't responded me with the results yet, but I tested it on my machine running the server with the JVM flag `-Duser.language=tr` and it isn't working. It shows the same error.

![image](https://user-images.githubusercontent.com/62086445/216555587-7c71cd55-08cb-4bcc-885c-b535d544916f.png)

**Comment by AkashiiKun** [comment]
Then I don't understand why is happening, because the variant doesn't even have accent, is called "lucia".
https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/blob/ff295aece8b44fa77299bdd6cc7beed3fda33372/Common/src/main/java/io/github/akashiikun/mavm/AxolotlVariants.java#L18

**Comment by jmadarg** [comment]
I did some digging and it seems that the problem is because of Turkish using special characters (`I` with a dot and `i` without a dot) so the method `toLowerCase()` is actually converting `I` to `i` without the dot and I noticed you were using `toLowerCase(Locale.ROOT)` on the file you sent, which has the same behavior.

Not sure why the fabric server doesn't like that, but the top answer on this [stackoverflow question](https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase) recommends to use `toLowerCase(Locale.ENGLISH)` to force the expected `I` to `i` conversion, ignoring the user locale.

Tried to test it, but didn't manage to clone and build the project correctly, I'm still too new to Java.

**Comment by AkashiiKun** [comment]
Ok, just did that change. Hope it's fixed now.
[More Axolotl Variants Mod Locale Fix 2.zip](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10663973/More.Axolotl.Variants.Mod.Locale.Fix.2.zip)

**Comment by jmadarg** [comment]
Tried it, the issue persist.
![image](https://user-images.githubusercontent.com/62086445/217107931-669fd0d0-4d08-40ea-a0ed-69cc157672af.png)
Maybe that first call to `toLowerCase()` is messing with it, as its not specified to use English?

**Comment by AkashiiKun** [comment]
Didn't realize i've put that.
[More Axolotl Variants Mod Locale Fix 3.zip](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10678397/More.Axolotl.Variants.Mod.Locale.Fix.3.zip)

**Comment by jmadarg** [comment]
It works fine now! Thanks!

**Comment by AkashiiKun** [comment]
Pushed in latest update.
